coverage:
  stage: coverage
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-tmp
  needs: [build_docker_test, unit-tests]
  script:
    - coverage combine
    - coverage report --precision=2 -m
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
